# Generated by Django 6.0.7 on 2026-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('green', 'سبز'), ('brown', 'قهوه\u200cای'), ('orange', 'نارنجی'), ('blue', 'آبی'), ('amber', 'کهربایی'), ('teal', 'سبزآبی')], default='green', max_length=20, verbose_name='رنگ کارت'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('droplets', 'قطره آب — محلول\u200cهای آبیاری'), ('mountain', 'کوه — خاک و بستر کاشت'), ('flask-conical', 'فلاسک — کودهای شیمیایی'), ('leaf', 'برگ — محصولات طبیعی'), ('wheat', 'گندم — غلات'), ('sprout', 'جوانه — بذر و نهال'), ('trees', 'درخت — درختان و باغبانی'), ('flower-2', 'گل — گل و گیاه زینتی'), ('bug', 'حشره — سموم و آفت\u200cکش'), ('shovel', 'بیل — ابزار کشاورزی'), ('sun', 'خورشید — گلخانه'), ('cloud-rain', 'باران — تجهیزات آبیاری')], default='sprout', help_text='در صورت آپلود آیکون سفارشی، این گزینه نادیده گرفته می\u200cشود', max_length=50, verbose_name='آیکون (Lucide)'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='فایل PNG یا SVG آیکون دلخواه (اولویت با این فیلد است)', null=True, upload_to='categories/icons/', verbose_name='آیکون سفارشی'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, help_text='برای نمایش در کارت دسته\u200cبندی صفحه اصلی', max_length=150, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
