# Generated by Django 6.0.8 on 2026-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_category_color_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='لینک ویدیوی معرفی (YouTube / Instagram)'),
        ),
    ]
